[package]

name = "tclscan"
version = "0.0.1"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

build = "src/build.rs"

[build-dependencies]
bindgen = "= 0.63.0"

[dependencies]
docopt = "1.1"
enum_primitive = "0.1"
num = "0.4"
rustc-serialize = "0.3"

[[bin]]

name = "tclscan"
